### ISSUE TITLE
When clicking on a series, it does not show any multimedia objects

### ISSUE THREAD

**Issue by Alfro** [teltek/PumukitStatsUIBundle#9]
After searching for a series in **General Statistics for Series**, when clicking on the found series, no objects appear on screen:
![screen2_rescaled](https://cloud.githubusercontent.com/assets/11334172/14287965/239131be-fb55-11e5-88f0-2346c217d25d.gif)

This is caused by the filter not being reseted, as it ca be seen in the .gif. But it is still not a good UX to enter a series and find it empty.

**Options are:**
- Reset the filter after clicking on a series.
- Showing 'Not objects found with these values.' to hint that the problem might be the filters.
- Do both.

**Comment by silviabf** [comment]
This bug is fixed in branch master (to apply in the new Pumukit release). @Alfro closes this issue.
